package com.example.mnnit_fc.core.enums;

public enum AcademicBranch {
    COMPUTER_SCIENCE_AND_ENGINEERING,
    ELECTRONICS_AND_COMMUNICATION_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    CHEMICAL_ENGINEERING,
    PRODUCTION_AND_INDUSTRIAL_ENGINEERING,
    BIOTECHNOLOGY,
    INFORMATION_TECHNOLOGY,
    MCA,
    MBA
}
